site_name: RUYTER.ORG (dms)
site_author: Peter de Ruyter
site_description: Personal Documentation Hub

site_url: https://dms.ruyter.org
repo_url: https://github.com/ruyterpde

copyright: RUYTER.ORG © 2025

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: red

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: red

  features:
    - content.code.annotate
    - content.code.copy
    - content.links.external
    - navigation.indexes
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlights
    - content.tab.link

  language: en

# Removed invalid property 'draft_docs'

plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ruyterpde
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/pderuyter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/pderuyter
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ruyterpde
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pderuyter

extra_javascript:
  - javascripts/external-links-new-tab.js

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

watch:
  - includes
